### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Smileyone** [UniversalDevicesInc/polyglot-v2#100]
I installed a linux-x64 version of Polyglot-v2 on a Ubuntu 20.04.2 VM and I can't get the nodes servers to work correctly.  The log states ModuleNotFoundError: No module named 'polyinterface' or 'pgc_interface'.  Are there files missing in my installation?
Any assistance would be greatly appreciated.
Thank you.

I've attached the log file.
[polyglot_2-6-2021_45039_PM.txt](https://github.com/UniversalDevicesInc/polyglot-v2/files/5937737/polyglot_2-6-2021_45039_PM.txt)

**Comment by jimboca** [comment]
The install.sh for the nodeserver should have installed polyinterface. Did you install the nodeserver from the store?

**Comment by Smileyone** [comment]
Yes, I installed the nodeserver from the store and this is what the log says.

2/7/2021, 9:40:18 AM [polyglot] info: MQTTS: Client Connected:
2/7/2021, 9:40:18 AM 
[polyglot] info: MQTTP: Frontend Websockets interface Connected. 
2/7/2021, 9:43:57 AM [polyglot] info: NSChild cloneRepo: Successfully cloned AERISWeather into NodeServer directory.
2/7/2021, 9:43:57 AM [polyglot] error: NSChild: Install failed - Non-zero exit code: 127
2/7/2021, 9:43:57 AM [polyglot] error: NSChild: AERISWeather cloneRepo: Error: runInstallProcess: undefined
2/7/2021, 9:43:57 AM [polyglot] error: Error: runInstallProcess: undefined
    at runInstallProcess (/snapshot/polyglot-v2/lib/modules/children.js:45:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2/7/2021, 9:43:57 AM [polyglot] error: NSResponse: Success: false - cloneRepo: Error: runInstallProcess: undefined

**Comment by jimboca** [comment]
Run the install.sh for the nodeserver manually since Polyglot doesn't show the actual error.

**Comment by Smileyone** [comment]
I ran the install.sh manually and the error is "pip3: command not found"

**Comment by jimboca** [comment]
Well that explains it. You need to install python 3

**Comment by Smileyone** [comment]
I'll do that, thank you.
