### ISSUE TITLE
Where is 2.2.11 linux binary on AWS?

### ISSUE THREAD

**Issue by psmith3** [UniversalDevicesInc/polyglot-v2#103]
Looking for the 2.2.11 binary for Linux and all I see is /2.2.11/polyglot-v2-freebsd-x64.tar.gz. Is that file replacing the linux-x64 file?

https://s3.amazonaws.com/polyglotv2

**Comment by jimboca** [comment]
Not sure if all were rebuilt but RPi is here https://s3.amazonaws.com/polyglotv2/binaries/polyglot-v2-linux-armv7.tar.gz

**Comment by psmith3** [comment]
Thanks. I'm running it on my Synology NAS that has an Atom processor. Have not tried to see if Arm will run on it and not sure but I will give it a try.

**Comment by psmith3** [comment]
Nope, it will not work. I am building a Docker container to run it in and get the following error. "/opt/udi-polyglotv2/polyglot-v2-linux-armv7: cannot execute binary file: Exec format error". 2.2.10 worked using the Linux-x64 version, but I noticed some weird issues like the front-end version not matching. Looks like I need a Linux binary for 2.2.11.

**Comment by jimboca** [comment]
Yes I figured, need to ask @exking to build it

**Comment by psmith3** [comment]
Thanks @jimboca. @exking, would you be able to build a 2.2.11 linux-x64 binary and place it in the appropriate AWS directory?

**Comment by exking** [comment]
sure, done. I've built it on Ubuntu 20.04 though, if that does not work - you can either rebuild yourself or just run from source. Binary is not really needed to run it :)

**Comment by psmith3** [comment]
Thanks @exking. I too am seeing this SSL error 2.2.11 running in a Docker container. Have you seen this issue? 
error: Startup error. Shutting down: Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small.

I see an open issue related to "ee key too small" and replied under that issue.

**Comment by exking** [comment]
I think @Einstein42 reported it here https://github.com/jfromaniello/selfsigned/issues/33 It's an issue with the library he originally used to generate the certificates.

**Comment by psmith3** [comment]
Ok. Thanks. I guess for now, I will try to disable SSL since my machine is only running on my private network.
