### ISSUE TITLE
How do I uninstall polyglot-v2?

### ISSUE THREAD

**Issue by pgattu** [UniversalDevicesInc/polyglot-v2#3]
I installed polyglot-v2 on a Raspberry Pi I am using for Pi-Hole.  Installing polyglot made the Pi-Hole very slow.  I need help to uninstall all of polyglot-v2, so I can install it on a separate, new Raspberry Pi.

**Comment by exking** [comment]
you would need to stop polyglot and mongodb first line
```
sudo systemctl stop polyglot-v2
sudo systemctl disable polyglot-v2
sudo systemctl stop mongodb
sudo systemctl disable mongodb
```

remove all polyglot files
rm -rf polyglot .polyglot

uninstall any packages you've previously installed for polyglot using `apt-get purge`

**Comment by pgattu** [comment]
After uninstalling using above instructions, I did the following:

1) Uninstall mongodb using `sudo apt-get remove mongodb-server`
2) Remove Node Server files using `rm -rf .pip`
3) Reboot the operating system.  Otherwise, the web application for Polyglot was still running, i.e. https://my_polyglot was still returning Polyglot pages.  After reboot, the web application is not running anymore.
