### ISSUE TITLE
Error installing Roomba NodeServer

### ISSUE THREAD

**Issue by pgattu** [UniversalDevicesInc/polyglot-v2#5]
I installed the Roomba NodeServer from the NodeServer Store.  I see the following error in the debug log.  Please help.

2018-2-6 19:22:33 - info: NS: Successfully cloned Roomba into NodeServer directory.
2018-2-6 19:22:33 - error: NSChild: Roomba /usr/bin/env bash -xe ./install.sh: + pip3 install -r requirements.txt --user

2018-2-6 19:22:42 - error: NSChild: Roomba install error: Non-zero exit code: 1

**Comment by pgattu** [comment]
I found the following at the end of the pip.log file:

  Could not find any downloads that satisfy the requirement opencv-python (from Roomba980-Python==1.2.1->-r requirements.txt (line 3))
Cleaning up...
No distributions at all found for opencv-python (from Roomba980-Python==1.2.1->-r requirements.txt (line 3))
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
pip.exceptions.DistributionNotFound: No distributions at all found for opencv-python (from Roomba980-Python==1.2.1->-r requirements.txt (line 3))

**Comment by exking** [comment]
Please create this issue for the [Roomba NodeServer](https://github.com/fahrer16/udi-roomba-poly), not for the Polyglot itself.
