### ISSUE TITLE
delNode not working

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc/polyglot-v2#50]
Calling delNode like this:

```
fnode = self.controller.poly.getNode(sensorAddressOld)
self.controller.delNode(fnode['address'])
```

results in this in the polyglot log...

```
2018-12-9 20:14:51 - debug: MQTTP: nsCommand Message: {"removenode" {"address":"ei0"},"node":"11"}
2018-12-9 20:14:51 - info: Ecobee(11): Processing command: removenode
2018-12-9 20:14:52 - debug: ISY: 400 - http://192.168.86.64:80/rest/ns/undefined/nodes/ei0/remove
2018-12-9 20:14:52 - error: removenode: Error: ISY sent invalid result code.
    at Object.removenode (/snapshot/polyglot-v2/lib/modules/nodeserver.js:445:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by bpaauwe** [comment]
Does this: https://github.com/UniversalDevicesInc/polyglot-v2/pull/49/commits/6af9f392502a9e57adcc702cda638d1685688a12 help?

**Comment by jimboca** [comment]
No idea, will need to look at the code and what ISY expects, but thanks for the pointer.

**Comment by jimboca** [comment]
The nodeserver guide says:

> /nodes/\<nodeAddress\>/remove
> Removes a node from the ISY. A node cannot be removed if it is the primary
> node for at least one other node.
> nodeAddress The full address of the node (e.g. ‘n005_dimmer_1’)
> E.g. /rest/ns/5/nodes/n005_dimmer_2/remove

But it's sending:
> http://192.168.86.64:80/rest/ns/undefined/nodes/ei0/remove

So looks like it needs to call that addNodePrefix, and pass the profilenum instead of undefined.

I really wish there was a rename function, but will have to use remove and add instead which will annoy users...

**Comment by jimboca** [comment]
@bpaauwe I just saw your pull request...  https://github.com/UniversalDevicesInc/polyglot-v2/pull/49

Will that fix the issues?

**Comment by bpaauwe** [comment]
That's what I was asking. I'm not sure. It kind of sounds like it might, but your case is different that what I was seeing.  It looks more like what I was trying to fix initially with the missing profile prefix on the address.   The second fix was to prevent adding the prefix when it already had one.

It should be easy to apply the commit and see if it helps.

**Comment by jimboca** [comment]
Ya sorry, I realized that's what you were asking after noticing that.  I don't think your change will fix it, but other changes in the unreleased code may  fix the /undefined/ part.  Guess I'll need to grab the latest and run from the source.

**Comment by jimboca** [comment]
So I tested with the current edev and it works correctly.  I also tested with bpaauwe/polyglot-v2 edev-fixes and it also works.

We really need to get the current edev released...  The only issue I notice is that when running from source I notice that when I "stop" a nodeserver it doesn't seem to really stop?
