### ISSUE TITLE
The "encryption" class does nothing of value

### ISSUE THREAD

**Issue by NickBorgers** [UniversalDevicesInc/polyglot-v2#56]
https://github.com/UniversalDevicesInc/polyglot-v2/blob/f92a0db6894e7f9015224d6d3fa04dda9cd42a36/lib/modules/encryption.js#L4

The variable called "encoding" is actually the password used to derive the cryptographic key, which is both static across all installations and published on GitHub. This means it provides no value; all someone viewing the ciphertext needs to do is lookup this project and extract the key.

Incidentally [using AES without an initialization vector appears to have been deprecated by node](https://nodejs.org/api/crypto.html#crypto_crypto_createcipher_algorithm_password_options), but I wouldn't bother fixing that unless some form of localized key generation can be established.

I don't know what the purpose of this encryption was, but it's not fulfilling it.

**Comment by Einstein42** [comment]
Correct, this is on the todo list. Encryption is currently not implemented.
