### ISSUE TITLE
Add call to node/update REST command

### ISSUE THREAD

**Issue by Goose66** [UniversalDevicesInc/polyglot-v2#6]
Add a call to the /nodes//change/[?nls=] REST command to change the node_def_id for a node. Specific use case: user changes the units on a thermostat from Farenheit to Celcius and we want to switch the nodedef used instead of having the user delete and recreate the node in the ISY.

On the polyglotinterface side, add a method off of the Node such as changeNodeDefId(self, nodeDefID, nlsString=nothing)

**Comment by exking** [comment]
I don't think new method is warranted, existing updateNode() should update node def if it changed (most likely you'll be updating drivers as well so let's do it in 1 call)

**Comment by Goose66** [comment]
Won't be updating drivers. Just want the existing drivers to display in Celcius instead of farenheit. By switching the node_def_id associated with the nodes, I won't need to change anything in the MongoDB database or in the program logic, just changes whether the ISY puts a "C" next to the displayed driver value vs. an "F"

**Comment by Goose66** [comment]
Alright, I'm on board now. Have to switch the uom of the drivers as well as setting a new node_def_id, so updateNode is the way to go polyglotinterface. I guess polyglot will just have to check to see if the uom has changed from the database and call the node/update REST command accordingly if it has.

**Comment by Einstein42** [comment]
#14

**Comment by Goose66** [comment]
This is not working. It appears that the nodeUpdate() call does not call the REST change command if the node_def_id has changed. But if I call the REST change command manually, it works to change the node_def_id.
