### ISSUE TITLE
reportCommand() call is missing

### ISSUE THREAD

**Issue by exking** [UniversalDevicesInc/polyglot-v2#7]
nodes need to be able to report commands to ISY similar to report states.

**Comment by Einstein42** [comment]
I believe this is added in polyinterface, code was already there in Polyglot but will clean it up
2.1.1

**Comment by exking** [comment]
Fixed by [this](https://github.com/UniversalDevicesInc/polyglot-v2/commit/dbe420e345a8b671862b05a6ee823e19bc30a8aa#diff-a08154086aa666bcf11977517bac77d7), verified.
