### ISSUE TITLE
V2.2.6 with ecobee fails commands

### ISSUE THREAD

**Issue by larryllix** [UniversalDevicesInc/polyglot-v2#78]
After many deletions and reinstalls, polyglot and the ecobee NS finally came up and functioned fully last night.
Today, I noticed control programs on my ecobee stats not working again. Full status updates are still coming and tested, by setpoint manipulation on the stats.

Attempting manual controls on the admin console device page results in:
the first click = no response, 
the second click on the same command = "No response" from ISY.
repeatable every time.
The logs show no commands received but happily updates fields from the stats (2) with reports of success. These arethe same symptoms as I had before my last tear down and rebuild of polyglot 2.2.6.

[Ecobee_logs_2019-11-10_200531.zip](https://github.com/UniversalDevicesInc/polyglot-v2/files/3829730/Ecobee_logs_2019-11-10_200531.zip)

[PG_debug.log](https://github.com/UniversalDevicesInc/polyglot-v2/files/3829731/PG_debug.log)

**Comment by larryllix** [comment]
OK... zoomed in on the problem. 
The .env file was used properly in polyglot v2.2.4 but causes problems in v2.2.5, namely it will not accept commands from ISY to the Ecobee NS if the .env file exists.
I whittled the .env file down to no comments, and only one line, but any occurrence of the file cause the same problem. All statuses have updated despite any properly formatted lines in the .env file.

[full.env.txt](https://github.com/UniversalDevicesInc/polyglot-v2/files/3832261/full.env.txt)
[short.env.txt](https://github.com/UniversalDevicesInc/polyglot-v2/files/3832262/short.env.txt)

**Comment by jimboca** [comment]
I don't think it has anything to do with the env file.  I was testing 2.2.6 on my RPi and experienced the same issue, @Einstein42 and I tried to debug using my machine but couldn't figure it out, he is going to try and repeat on his end...

**Comment by larryllix** [comment]
I think it has to do with the "USE_HTTPS=false" line in the .env file. 
It functioned in v2.2.4 but broke my command comms from ISY to polyglot somehow.
I tried the file installed and removed several times and it failed when installed and worked and worked when removed every time.

**Comment by jimboca** [comment]
Something in 2.2.6 brok, it's an MQTT issue, I've run for months on 2.2.4 with no issue, and have had issues with 2.2.6 since installing on my RPi a few days ago, @Einstein42 will figure it out.

**Comment by larryllix** [comment]
I am running using https right now, with no problems that I can detect. It's just a PITA defeating the browser warning every time.

On a side note I found ISY deleted some of my ecobee programs when every line involved the MIA stats. grrrrr.....

**Comment by jimboca** [comment]
Like I said, nothing changed on my side, been using https always with no cert. Mine worked fine all day yesterday, and quit at 7am this morning.
I've never seen ISY delete programs.  But please don't use this to discuss random issues on this issue, it's hard enough to figure out what is up as is.

**Comment by mkohanim** [comment]
Is this only on RPi?

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by jimboca** [comment]
Larry is on Polisy and I'm on Rpi, might be different issues but they seem to be the same.

**Comment by mkohanim** [comment]
Thanks Jimbo. Can any of you please try PGC?

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by jimboca** [comment]
I have Ecobee running on PGC & pgtest, both are running fine.

**Comment by mkohanim** [comment]
So, the issue is when it’s run locally, correct?

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by jimboca** [comment]
I've been running Ecobee locally on 2.2.6 that came with the Polisy I received Saturday and I've had no issue.   It has a .env with only the one line
NODE_ENV=development

**Comment by mkohanim** [comment]
So, this is RPi only?

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by jimboca** [comment]
No @larryllix was on Polisy and did the manual beta upgrade, I'm on Polisy but with the shipped version.

**Comment by larryllix** [comment]
@jimboca It would possibly help if you tried the line 
"USE_HTTPS=false" line in the .env file, to see if that is the offender. 
It worked before the upgrade on v2.2.4
IIRC I have only tried the .env file as a minimum with that line, where polyglot fails,  and no .env file at all. where polyglot works fine. Never with any other line.

**Comment by jimboca** [comment]
@larryllix will do.  So you keep the port on 443 and connect with http://polisy:443 or did you change the default port to 80?

**Comment by larryllix** [comment]
@jimboca Correct. I could never manage to change the port to 80. When I reported problems somebody else forum posted that port 80 would not work. It was one of  the first lines to get commented out in .env

I was connecting with http://192.168.0.165:443

**Comment by mkohanim** [comment]
Nothing below port 443 will work.

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by jimboca** [comment]
@larryllix did you turn of 'SSL' in the Node Server Configuration on the ISY?

**Comment by larryllix** [comment]
No. I wasn't aware of that setting

**Comment by jimboca** [comment]
You told Polyglot to not use SSL, but ISY is still trying to use it.  I've asked @Einstein42 if he could consider fixing that automatically.

**Comment by larryllix** [comment]
OK. I thought you were referring in the ISY admin console. My bad.
There is no "use SSL" field in my polyglot.
There is a "Use https" checkbox.

**Comment by jimboca** [comment]
I was referring to ISY AC, under the "Node Server" -> "Configure" menu, you must turn off SSL for the Slots of the Polyglot instance that has USE_HTTPS=false.  It's not "Use SSL' it's just an "SSL checkbox.

**Comment by larryllix** [comment]
OMG. Too many similar definitions. LOL

Yes my SSL option is checked and was never changed by me at any point.

**Comment by jimboca** [comment]
Yes, as I mentioned, Polyglot turns that on when it creates the NS since it was in that mode, but then when you turn off https it doesn't disable that.  I asked @Einstein42 if that can be fixed.

**Comment by larryllix** [comment]
ahhh.. co-ordination problem between ISY settings and polyglot settings.

**Comment by larryllix** [comment]
So If I disable "Use SSL" in the ISY A/C NS setup and reinstall the "USE_HTTPS-false" line back into the .env file it should work?

Gotta take wife out for supper but may try that later tonight. 4:35 PM here.

**Comment by jimboca** [comment]
Yes, it works, I verified.

**Comment by larryllix** [comment]
Well "that's why you get the big bucks!" LOL Thanks for that one !

**Comment by larryllix** [comment]
One problem. The "USE_HTTPS=false" is documented as changing the browser access port and protocol, and shouldn't be related to ISY comms. 

It works just fine now with the line in .env.
