### ISSUE TITLE
ST value for controller not reported as 1 on Polyglot start

### ISSUE THREAD

**Issue by Goose66** [UniversalDevicesInc/polyglot-v2#8]
Had my RPi lock for some reason and had to power cycle it. On restart, Polyglot started back along with the nodeservers, and everything is find except one of my two nodeservers has a controller ST value of 0 and its not updating. Shows "False" in the Admin Console and "disconnected" in the Polyglot website Dashboard. I can see in the log for the nodeserver where it set the ST value of the controller to 1 and an entry in the Polyglot log - it's 4 seconds later where the Polyglot says successfully setting the value on the ISY to 1. However both the ISY Admin Console and the Dashboard showed the value as 0 after Polyglot start. I restart of the nodeserver clears it up.

**Comment by Einstein42** [comment]
I believe I found the issue, should be fixed in 2.1.1

**Comment by Einstein42** [comment]
Fixed in #14
