### ISSUE TITLE
Polisy fails to heal Ethernet connection break.

### ISSUE THREAD

**Issue by larryllix** [UniversalDevicesInc/polyglot-v2#92]
This has happened before but amidst other problems it didn't seem as clear what happened.

I installed a firmware update in my router and had to factory reset it. As a result, the router was down for maybe a half and hour. When it came back up my ISY was reporting failures of my ecobee NS stats and a few other comm issues. It seems polisy could not obtain an IP address from my router and gave up attempting to attach to my ISY as it had no IP address to do so. Out of about 55 devices my CAO Tag Manager failed to connect also.

My polisy and ISY sit on top of each other but have to go through a switch and this router to comm together.

Here is the polyglot logs, captured and trimmed from this event.

[polyglot_2020-4-9_011443.txt](https://github.com/UniversalDevicesInc/polyglot-v2/files/4463115/polyglot_2020-4-9_011443.txt)

Thanks guys and good luck!!

**Comment by jimboca** [comment]
@larryllix Why do you consider this a Polyglot problem?  Looks to me like a problem is your router not letting traffic thru, nothing much Polyglot can do if TCP/IP is not working...  Polisy has no control over the ethernet connection, it's either a router issue, or Polisy and/or ISY issue...

**Comment by larryllix** [comment]
Polisy gave up asking for an IP address to a working DHCP server that already served 51 other IP addresses. 
Then it attempted to communicate using a bad IP address 0.0.0.0 and appeared hung with a failed Ethernet port.

`2020-4-9 00:29:34 [polyglot] error: ISY: connection exceeded max re-tries. Aborting. Error: connect ENETUNREACH 192.168.0.161:80 - Local (0.0.0.0:34515)`

ISY would not respond to polisy sending out request packets with IP address of 0.0.0.0 as was shown in the log.

When I power cycled the polisy it requested an IP address again properly, got one, and everything resumed to normal again.

**Comment by larryllix** [comment]
Seems this was an ASUS router problem with too little NVRAM. Hasn't happened again  lately with new routers in place.
