### ISSUE TITLE
ISY username and password not being set by menu

### ISSUE THREAD

**Issue by Smileyone** [UniversalDevicesInc/polyglot-v2#96]
Hello,
I get this error message even after I set the ISY password via the menu: "ISY automatically discovered at https://192.168.50.6:444 however the username and password need to be set in the settings menu."
I've tried setting the password numerous times, restarted and reboot the RPi too.  It was working fine for months then stopped working.
Can you offer any assistance?
Thank you,
Joe

**Comment by Smileyone** [comment]
Found solution, thanks you.
Joe

**Comment by jtara** [comment]
Tell the rest of us the solution?

**Comment by Smileyone** [comment]
Sorry, I can't remember what I did to fix it.
